name: cibuildwheel
description: Run cibuildwheel to build manylinux wheels
branding:
  icon: package
  color: yellow

inputs:
  wheel-dir:
    description: Output wheel directory
    default: wheelhouse
runs:
  using: composite
  steps:
    - run: python -m pip install cibuildwheel==1.9.0
      shell: bash
    - run: python -m cibuildwheel --output-dir ${{ inputs.wheel-dir }}
      shell: bash
